#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from k_npu_bench.metrics import read_csv_rows, write_markdown_summary


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run a benchmark command repeatedly and summarize power efficiency.")
    p.add_argument("--cmd", required=True, help="Benchmark command to run. Quote it as one shell string.")
    p.add_argument("--repeat", type=int, default=3)
    p.add_argument("--csv", required=True, help="CSV generated by the benchmark command.")
    p.add_argument("--summary", default="results/power_efficiency_summary.md")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    for i in range(args.repeat):
        print(f"[{i + 1}/{args.repeat}] {args.cmd}")
        subprocess.run(args.cmd, shell=True, check=False)

    rows = read_csv_rows(args.csv)
    write_markdown_summary(
        args.summary,
        "Power Efficiency Summary",
        rows,
        ["latency_ms", "ttft_ms", "tpot_ms", "tokens_per_s", "fps", "avg_power_w", "energy_j", "tokens_per_j", "fps_per_w", "peak_memory_mb"],
    )
    print(f"Wrote {args.summary}")


if __name__ == "__main__":
    main()

